# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - langunana-backend

on:
  push:
    branches:
      - main   # ðŸ‘ˆ apni branch daalna, agar alag hai to
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: backend   # ðŸ‘ˆ yaha backend folder me jayega
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Optional: Run your tests
      # - name: Run tests
      #   working-directory: backend
      #   run: pytest

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E7C02CD651F04E7589E8EBE4EC4FC5C9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_21B2DF10BD52468AB9C27D0EBA5256ED }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_183CFF40144747E89A92A4D84AECBC4E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'langunana-backend'   # ðŸ‘ˆ apna App Service ka naam
          slot-name: 'Production'
          package: backend/   # ðŸ‘ˆ direct backend folder deploy hoga

